### ISSUE TITLE
Paper page returns 404

### ISSUE THREAD

**Issue by smacz42** [Electron-Cash/electroncash.org#20]
I got a 404 when navigating to https://electroncash.org/paper

Code seems to be here:

https://github.com/Electron-Cash/electroncash.org/blob/2a6af845a5603ba70888c808de98f0a84d144432/index.html#L394

IDK the history, or where would be the best place to have this pointing.

**Comment by imaginaryusername** [comment]
Made a pull request https://github.com/Electron-Cash/electroncash.org/pull/31
